---
- name: Add apt reporitory key for mysql
  apt_key:
    url: "https://repo.mysql.com/RPM-GPG-KEY-mysql"
    state: present
    keyring: /etc/apt/trusted.gpg.d/mysql.gpg

- name: Add mysql apt repository (Debian)
  apt_repository:
    repo: deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7
    state: present
    update_cache: yes

- name: install MySQL
  apt: name=mysql-server state=present

- name: Prepare MySQL config
  template:
    src: "mysqld.cnf.j2"
    dest: "/etc/mysql/mysql.conf.d/mysqld.cnf"

- name: Remove password for root
  command: mysql -u root -Ns -e "update mysql.user set authentication_string=password(''), plugin='mysql_native_password' where user='root';"
  register: msg

- name: Create database
  command: mysql -u root -Ns -e "CREATE DATABASE IF NOT EXISTS `sylius` default charset utf8"

- name: Create back_office user
  command: mysql -u root -Ns -e "create user if not exists 'sylius'@'%' identified by 'sylius';"
  ignore_errors: yes

- name: Grant ALL privileges
  command: mysql -u root -Ns -e "grant all on *.* to 'sylius'@'%';"

- name: Flush privileges
  command: mysql -u root -Ns -e "flush privileges"

- name: restart mysql
  command: echo "restart mysql"
  notify: "restart mysql"
