---
- name: Install GPG key
  apt_key:
    url: "{{ neo4j.gpg_key_url }}"
    state: present

- name: Add neo4j repository
  apt_repository:
    repo: deb https://debian.neo4j.org/repo stable/
    state: present
    update_cache: yes
    filename: "neo4j_package"

- name: install neo4j
  apt:
    name: ['neo4j=1:3.4.8']
    state: present

- name: replace line
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^#dbms\.connectors\.default_listen_address'
    line: 'dbms.connectors.default_listen_address=0.0.0.0'

- name: restart neo4j
  command: echo "restart neo4j"
  notify: "restart neo4j"
